### ISSUE TITLE
package com.intellijava.com.intellijava.core.controller does not exist

### ISSUE THREAD

**Issue by Skandy1** [Barqawiz/IntelliJava#1]
I am trying to integrate this plugin onto my maven project, I have tried both the ways suggested by you but, it looks like the plugin is not being fetched when I perform `clean install`. Please let me know if I am doing something wrong here, thanks.

PFA for the error:

![Screenshot 2023-01-10 at 10 31 58 AM](https://user-images.githubusercontent.com/23314608/211465995-86cb9f37-7980-4f9d-be0d-06182327806d.png)

I have added the plugin as an external library

![Screenshot 2023-01-10 at 10 32 51 AM](https://user-images.githubusercontent.com/23314608/211466098-25de667b-22d7-4762-a2e6-8e51224d5cf7.png)

I tried adding it as a maven dependency as well

![Screenshot 2023-01-10 at 10 55 03 AM](https://user-images.githubusercontent.com/23314608/211468730-8a807757-0b35-4a9e-a1d4-28eedf7ef72a.png)

**Comment by Barqawiz** [comment]
The issue your code trying to read the package from repo.maven.apache.org/maven2 not from the Github packages.

This is the documentation to install a package published only in Github:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#authenticating-to-github-packages

**Comment by Barqawiz** [comment]
I updated the documentation [here](https://github.com/Barqawiz/IntelliJava/packages/1767035?version=0.3), kindly check and tell me if works with you.

**Comment by Skandy1** [comment]
This was really helpful, thanks.
