### ISSUE TITLE
[question] how do we ask continuously?

### ISSUE THREAD

**Issue by umjammer** [Barqawiz/IntelliJava#3]
on ChatGPT web we can ask multiple times keeping conversation context.
how do we do using this library?

below doesn't work well (context seems to be reset every time) .
```java
        while (true) {
            System.out.print("Q: ");
            String prompt = new BufferedReader(new InputStreamReader(System.in)).readLine();
            LanguageModelInput langInput = new LanguageModelInput.Builder(prompt)
                    .setModel(chatGptModel)
                    .setTemperature(0.5f)
                    .setMaxTokens(1024).build();
            String resValue = langModel.generateText(langInput);
            System.out.println("A:");
            System.out.println(resValue);
        }
```

**Comment by Barqawiz** [comment]
To keep the conversation context you have to keep loading the last n questions and answers in the conversation.
Make sure the maximum number of tokens to load does not exceed the value in setMaxTokens.

Your prompt to the model will look like this, where xxxx represents previous questions and answers:
Q: xxxx
A: xxxx
Q: xxxx
A: xxxx
Q: <current_user input>
A:

**Comment by umjammer** [comment]
i dug into your source code. then i found this project uses `https://api.openai.com`.
i got it. thanks.
