### ISSUE TITLE
Great library hope it will add more features

### ISSUE THREAD

**Issue by eix128** [Barqawiz/IntelliJava#8]
Hi , thanks for sharing such a library.
I want tts for Chinese  , Turkish support on code :
how to use tts for turkish or chinese or other langs ?
model.generateGoogleText seems private field.

        // 1- initiate the remote speech model
        RemoteSpeechModel model = new RemoteSpeechModel("xxxxxxxxxxxxxxxx", SpeechModels.google);
        List<String> supportedModels = model.getSupportedModels();

        // 2- call generateEnglishText with any text
        Text2SpeechInput input = new Text2SpeechInput.Builder("Hi, I am Intelligent Java.").build();

        byte[] decodedAudio = model.generateEnglishText(input); 

Also it would be good to add    STT (speech to text) library into this library

I have added patch to select playerCode 

	public byte[] generateGoogleText(String text, Gender gender , String playerCode , String language ) throws IOException {
		byte[] decodedAudio = null;

		Map<String, Object> params = new HashMap<>();
		params.put("text", text);
		params.put("languageCode", language);

		if (gender == Gender.FEMALE) {
			params.put("name", "en-GB-Standard-A");
			params.put("ssmlGender", "FEMALE");
		} else {
			params.put("name", "en-GB-Standard-B");
			params.put("ssmlGender", "MALE");
		}

		if(playerCode != null) {
			params.put("name",playerCode);
		}

		AudioResponse resModel = (AudioResponse) wrapper.generateSpeech(params);
		decodedAudio = AudioHelper.decode(resModel.getAudioContent());

		return decodedAudio;
	}

**Comment by Barqawiz** [comment]
Thanks for the feedback, the library is updated to support Turkish & Chinese in version 0.8.2.

Let me know if the speech model works as expected. 

Can you elaborate the intended use of the playerCode ?

**Comment by eix128** [comment]
Its used for selecting the voice names:
for turkish example :
"tr-TR-Wavenet-E"

Look at all:
https://cloud.google.com/text-to-speech/docs/voices

**Comment by Barqawiz** [comment]
Ok thanks, you mean the voice name.

For now you can send the language code for Turkish and Chinese through following functions:

- generateText(Text2SpeechInput input, String langCode)
- OR generateTurkishText(Text2SpeechInput input) 
- OR generateMandarinText(Text2SpeechInput input) 

And in the next versions will provide a more flexible approach.
